version: 'latest'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      -POSTGRES_USER: baonguyen
      -POSTGRES_PASSWORD: 123
      -POSTGRES_DB: leh-database
      -PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres

volumes:
  postgres:

